### ISSUE TITLE
Disabling mods crashes client (1 day)

### ISSUE THREAD

**Issue by edcabrera** [the-dargon-project/dargon-root#5]

**Comment by miyu** [comment]
Failed to reproduce on desktop. Will try on laptop later.

**Comment by miyu** [comment]
Reproduced, seems to happen randomly similar to our progress bar code.

See previous comment:

```
DataContext randomly changes to MS.Internal.NamedObject 
see: http://stackoverflow.com/questions/20124604/cant-convert-object-of-type-ms-internal-namedobject-to-system-windows-datatempl
```

at https://github.com/the-dargon-project/the-dargon-project/blob/master/dargon-client/Views/ModificationEntryProgressIndicator.xaml.cs#L33

Stack trace:

``` csharp
System.Windows.ResourceReferenceKeyNotFoundException was unhandled
  HResult=-2146233079
  Message='ModificationDisabledColor' resource not found.
  Source=PresentationFramework
  StackTrace:
       at MS.Internal.Helper.FindResourceHelper.DoTryCatchWhen(Object arg)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at MS.Internal.Helper.FindResourceHelper.TryCatchWhen()
       at System.Windows.FrameworkElement.FindResource(Object resourceKey)
       at Dargon.Client.Views.ModificationEntryProgressIndicator.GetCurrentStatusColor() in V:\my-repositories\dargon-root\dargon\dargon-client\Views\ModificationEntryProgressIndicator.xaml.cs:line 93
       at Dargon.Client.Views.ModificationEntryProgressIndicator.<UpdateProgressBarColor>b__10_1() in V:\my-repositories\dargon-root\dargon\dargon-client\Views\ModificationEntryProgressIndicator.xaml.cs:line 76
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at Dargon.Client.DargonClientApplication.UserInterfaceThreadStart() in V:\my-repositories\dargon-root\dargon\dargon-client\DargonClientApplication.cs:line 89
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```
